name: ChatGPT Review
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ChatGPT Review
        run: |
          npm install openai
          node .github/scripts/review.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 


# name: C/C++ CI

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: sed
#       run: sed -i 's/\r$//' configure
#     - name: configure
#       run: bash ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
